<?php

/**
 * Implementation of hook_menu()
 */
function dna_menu() {
  $items = array();

  $items['dna/export'] = array(
    'title' => 'Export all',
    'description' => 'Export fingerprint',
    'page callback' => 'dna_export',
    'access arguments' => array('administer content'),
    'type' => MENU_NORMAL_ITEM,
   );

  return $items;
}


function dna_export() {
  module_load_include('inc', 'dna', 'output_php');
  return '';
}

