<?php

/**
 * Implementation of hook_menu()
 */
function dna_menu() {
  $items = array();

  $items['dna/export'] = array(
    'title' => 'Export all',
    'description' => 'Export fingerprint',
    'page callback' => 'dna_export',
    'access arguments' => array('administer content'),
    'type' => MENU_NORMAL_ITEM,
   );

  return $items;
}


function dna_export() {
  module_load_include('inc', 'dna', 'dna_output_xml');

  $exporter = new dna_xml();
  return $exporter->get_output();
}


/**
 * Implementation of hook_node_info()
 */
function dna_node_info() {
  return array(
    'dna' => array(
      'name' => t('Site dna'),
      'module' => 'dna',
      'description' => t('Export a site dump from exportables'),
      'has_title' => TRUE,
      'has_body' => TRUE,
    )
  );
}


/**
 * Implementation of hook_form().
 * Form for the dna node type
 */
function dna_form(&$node) {
  $form = array();
  $form['title'] = array(
    '#title' => t('Title'),
    '#type' => 'textfield',
    '#disabled' => TRUE,
    '#value' => isset($node->title) ? $node->title : t('Site dump at @time', array('@time' => time())),
  );

  module_load_include('inc', 'dna', 'dna_settings');

  $exporter = new dna_settings();

  $form['body'] = array(
    '#title' => t('Body'),
    '#type' => 'textarea',
    '#disabled' => TRUE,
    '#value' => isset($node->body) ? $node->body : $exporter->get_output(),
  );

  return $form;
}


/**
 * Implementation of hook_nodeap().
 *
 * @todo make the node load and display nicer
 */
function dna_nodeapi(&$node, $op, $teaser, $page) {
  if ($node->type != 'dna') {
    return;
  }

  /**
   * Save the dna before the html filter screws it up
   */
  if ($op == 'load') {
    $node->dna = unserialize($node->body);
  }

  if ($op == 'view') {
    module_load_include('inc', 'dna', 'dna_output_xml');
    $exporter = new dna_xml($node->dna);

    if ($teaser) {
      $exporter->set_modules(array());
      $exporter->set_variables(array());
      $exporter->set_enabled_modules(array());
      $node->content['teaser']['#value'] = dna_xml::format_xml($exporter->get_output());
      $node->content['body'] = '';
    } else {
      $node->content['body']['#value'] = dna_xml::format_xml($exporter->get_output());
    }
  }

}
