<?php

define('FINGERPRINT_DEFAULT_DOMAIN', 'http://localhost/dnastore/');
define('FINGERPRINT_DEFAULT_SERVER', FINGERPRINT_DEFAULT_DOMAIN .'?q=services/xmlrpc');
define('FINGERPRINT_FILTERED_ELEMENT', '[FILTERED]');

/**
 * Implementation of hook_menu()
 */
function fingerprint_menu() {
  $items = array();

  $items['node/%node/fingerprint_send'] = array(
    'title' => 'Send to pronovix',
    'page callback' => 'fingerprint_send',
    'page arguments' => array(1),
    'type' => MENU_LOCAL_TASK,
    'access callback' => '_fingerprint_send_permission',
    'access arguments' => array(1),
  );

  $items['admin/settings/fingerprint'] = array(
    'title' => 'Fingerprint configuration',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('fingerprint_settings_form'),
    'type' => MENU_NORMAL_ITEM,
    'access arguments' => array('administer site configuration'),
  );

  return $items;
}


function _fingerprint_send_permission($node) {
  return _node_is_fingerprint($node) && user_access('send fingerprint content trough xmlrpc') && !module_exists('dna_server');
}


/**
 * System settings form of the module
 */
function fingerprint_settings_form($form_state) {
  $form = array();

  $form['fingerprint_server'] = array(
    '#type' => 'textfield',
    '#title' => t('Server'),
    '#default_value' => variable_get('fingerprint_server', FINGERPRINT_DEFAULT_SERVER),
    '#description' => t('If you want to use your own fingerprint store, the following services permissions should be enabled: %permissions', array('%permissions' => 'system.connect, user.login, node.save')),
    '#required' => TRUE,
  );

  $form['fingerprint_domain'] = array( // We're using the username as the domain as well
    '#type' => 'textfield',
    '#title' => t('Username'),
    '#default_value' => variable_get('fingerprint_domain', ''),
    '#required' => TRUE,
  );

  $form['fingerprint_password'] = array(
    '#type' => 'password',
    '#title' => t('Password'),
    '#default_value' => variable_get('fingerprint_password', ''),
    '#required' => TRUE,
  );

  $form['fingerprint_key'] = array(
    '#type' => 'textfield',
    '#title' => t('Api key'),
    '#default_value' => variable_get('fingerprint_key', ''),
    '#required' => TRUE,
  );

  return system_settings_form($form);
}


/**
 * Sends the node to the Pronovix server
 *
 * @todo store remote nid
 */
function fingerprint_send($node) {
  $url = variable_get('fingerprint_server', FINGERPRINT_DEFAULT_SERVER);
  $domain = variable_get('fingerprint_domain', '');
  $key = variable_get('fingerprint_key', '');
  $username = $domain;
  $password = variable_get('fingerprint_password', '');

  if (empty($url) || empty($domain) || empty($key) || empty($password)) {
    return t('First you have to set up your credentials: !url', array('!url' => l('Fingerprint settings', 'admin/settings/fingerprint')));
  }

  module_load_include('inc', 'fingerprint', 'fingerprint_xmlrpc');
  $xmlrpc_handler = new FingerprintXmlrpc($domain, $key, $url);
  $user = $xmlrpc_handler->userLogin($username, $password);
  if (!$user) {
    return t('Authentication failed: %message', array('%message' => xmlrpc_error_msg()));
  }

  unset($node->fingerprint);
  unset($node->nid);
  $node->uid = $user->uid;
  /** @todo check on server also **/
  $node->status = FALSE;
  $node = $xmlrpc_handler->send('node.save', array($node));
  if (!$node) {
    return t('Failed to save node: %message', array('%message' => xmlrpc_error_msg()));
  }

  // If we own the domain we can provide nice url
  if (strpos($url, FINGERPRINT_DEFAULT_DOMAIN) !== FALSE) {
    $node_path = FINGERPRINT_DEFAULT_DOMAIN .'?q=node/'. $node;
    return t('Node saved as !url', array('!url' => l('node/'. $node, $node_path)));
  }

  return t('Node saved as node/%nid', array('%nid' => $node));
}


/**
 * Checks if the node type is fingerprint
 *
 * @return bool True if it's a fingerprint site dump, else otherwise
 *
 */
function _node_is_fingerprint($node) {
  return $node->type == 'fingerprint';
}


/**
 * Implementation of hook_node_info()
 */
function fingerprint_node_info() {
  return array(
    'fingerprint' => array(
      'name' => t('Site fingerprint'),
      'module' => 'fingerprint',
      'description' => t('Export a site dump from exportables'),
      'has_title' => TRUE,
      'has_body' => TRUE,
    )
  );
}


/**
 * Implementation of hook_form().
 * Form for the fingerprint node type
 */
function fingerprint_form(&$node) {
  $form = array();
  $form['title'] = array(
    '#title' => t('Title'),
    '#type' => 'textfield',
    '#disabled' => TRUE,
    '#value' => isset($node->title) ? $node->title : t('Site dump at @time', array('@time' => time())),
  );

  module_load_include('inc', 'fingerprint', 'fingerprint_settings');

  $exporter = new FingerprintSettings();

  $form['body'] = array(
    '#title' => t('Body'),
    '#type' => 'textarea',
    '#disabled' => TRUE,
    '#value' => isset($node->body) ? $node->body : $exporter->getOutput(),
  );

  return $form;
}


/**
 * Implementation of hook_nodeap().
 *
 * @todo make the node load and display nicer
 */
function fingerprint_nodeapi(&$node, $op, $teaser, $page) {
  if ($node->type != 'fingerprint') {
    return;
  }

  /**
   * Save the fingerprint before the html filter screws it up
   */
  if ($op == 'load') {
    $node->fingerprint = unserialize($node->body);
    /**
     * This is the hook for filtering.
     * Ever exportable that you don't want to displayed should be set to
     * FINGERPRINT_FILTERED_ELEMENT constant in the tree (site email, etc).
     * @todo Create an interface so the user can do it dynamically
     */
    foreach (module_implements('fingerprint_filter') as $module) {
      $function = $module .'_fingerprint_filter';
      $function(&$node->fingerprint);
    }
  }

  if ($op == 'view') {
    module_load_include('inc', 'fingerprint', 'fingerprint_output_xml');
    $exporter = new FingerprintXml($node->fingerprint);

    if ($teaser) {
      $exporter->setModules(array());
      $exporter->setVariables(array());
      $exporter->setEnabledModules(array());
      $node->content['teaser']['#value'] = FingerprintXml::formatXml($exporter->getOutput());
      $node->content['body']['#value'] = '';
    } else {
      $node->content['body']['#value'] = FingerprintXml::formatXml($exporter->getOutput());
    }
  }

}


/**
 * Implementation of hook_perm().
 */
function fingerprint_perm() {
  return array(
    'create fingerprint content',
    'delete own fingerprint content',
    'delete any fingerprint content',
    'edit own fingerprint content',
    'edit any fingerprint content',
    'send fingerprint content trough xmlrpc',
  );
}


/**
 * Implementation of hook_access().
 */
function fingerprint_access($op, $node, $account) {
  if ($op == 'create') {
    return user_access('create fingerprint content', $account);
  }

  if ($op == 'update') {
    if (user_access('edit any fingerprint content', $account) || (user_access('edit own fingerprint content', $account) && ($account->uid == $node->uid))) {
      return TRUE;
    }
  }

  if ($op == 'delete') {
    if (user_access('delete any fingerprint content', $account) || (user_access('delete own fingerprint content', $account) && ($account->uid == $node->uid))) {
      return TRUE;
    }
  }
}


/**
 * @see services_get_hash()
 */
function _fingerprint_get_hash($timestamp, $domain, $api_key, $nonce, $method, $args) {
  $hash_parameters = array($timestamp, $domain, $nonce, $method);
  return hash_hmac("sha256", implode(';', $hash_parameters), $api_key);
}


/**
 * Implementation of hook_fingerprint_filter().
 *
 * @todo return an array instead and filter recursively by the module
 *
 * By default it filters:
 * * Site email address
 * * drupal_private_key
 * * Fingerprint settings
 */
function fingerprint_fingerprint_filter(&$fingerprint) {
  $fingerprint['variables']['site_mail'] = FINGERPRINT_FILTERED_ELEMENT;
  $fingerprint['variables']['drupal_private_key'] = FINGERPRINT_FILTERED_ELEMENT;
  $fingerprint['variables']['drupal_private_key'] = FINGERPRINT_FILTERED_ELEMENT;
  $fingerprint['variables']['fingerprint_domain'] = FINGERPRINT_FILTERED_ELEMENT;
  $fingerprint['variables']['fingerprint_password'] = FINGERPRINT_FILTERED_ELEMENT;
  $fingerprint['variables']['fingerprint_key'] = FINGERPRINT_FILTERED_ELEMENT;
}

